version: 2.1

#test

jobs:

  linting-testing:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - attach_workspace:
          at: .

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                chmod +x /bin/hadolint

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      # run lints!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint

      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test

  push-image-ecr:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      #- run: yum install -y tar
      #- run: yum install -y gzip

      - attach_workspace:
          at: .

      - setup_remote_docker

      - run:
          name: test build
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
            docker build -t udacity-capstone-project .

      #- run:
          #name: Build and push to ECR
          #command: |
            #aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 035472407210.dkr.ecr.us-east-1.amazonaws.com
            #docker build -t udacity-capstone-project .
            #docker tag udacity-capstone-project:latest 035472407210.dkr.ecr.us-east-1.amazonaws.com/udacity-capstone-project:latest
            #docker push 035472407210.dkr.ecr.us-east-1.amazonaws.com/udacity-capstone-project:latest


      
workflows:
  default:
    jobs:
      #- linting-testing
      #- push-image-ecr:
          #requires: [linting-testing]
      - push-image-ecr