apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: capstone-backend
          image: 035472407210.dkr.ecr.us-east-1.amazonaws.com/udacity-capstone-project:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-service
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    # - nodePort: 30000
    - port: 80
      targetPort: 5000